# Generated by Django 4.2.1 on 2023-07-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='item_qty',
            field=models.IntegerField(),
        ),
    ]
